### PR TITLE
feat!: better preview window with inccommand=split

### LINKED ISSUE #19: [Feature] Show a preview window listing all of the files and occurrences where the symbol will be replaced
It would be great for this plugin to show a rename preview panel similar to the quick fix one, containing a row for each of the symbols which will be updated with the LSP rename.

Also, those rows should be grouped in files where the change will occur. Example:

```
-----------------
-- Preview Window
-----------------

[1] C:\Work\include.h [1 match]
17. int NEWSYMBOL;

[2] C:\Work\main.c [2 matches]
19.   NEWSYMBOL = 12;
23.       print("Today is &d", NEWSYMBOL\n");
```

### PR DESCRIPTION
**Pull request by smjonas**
Closes #19.

Breaking change for users that use an old Nvim 0.8 nightly version that does not have vim.defaulttable yet.

@pidgeon777 Please try out this PR. This preview window will be shown when you `:set inccommand=split`. Do you think the relatively low height of the window is fine (7 lines for me, idk if it varies)? (I might be able to change the height after the preview buffer was created)

Here is how it looks like for me:
inc_rename_preview

### CODE REVIEW

**Comment by pidgeon777** [comment]
I just tested it, seems to be a significant improvement than before.

I would increase the preview window height, even better in two ways:
- Statically: by passing for example the wished preview window height in rows as an argument (or by setting a variable before running `IncRename`).
- Dynamically: count the number of rows according to the number of rows and files which are going to be changed and set the preview window height to display all of those items.

**Comment by smjonas** [comment]
Thanks a lot for testing this! I have not found a way to increase the height of the preview window yet (in fact I can't even get the preview window handle) so I will go ahead and merge this soon and improve it later. I've asked for help on the Nvim matrix server though.

**Comment by smjonas** [comment]
> I would increase the preview window height

I was told by famiu that apparently this is not currently possible.

**Comment by pidgeon777** [comment]
Let's hope one day it will be available as a feature, then 🤞.

**Comment by GitMurf** [comment]
> > I would increase the preview window height
> 
> I was told by famiu that apparently this is not currently possible.

Is it still not possible change increase the height of the preview window? I figured the option `previewheight` was exactly what I needed but I cannot get it to change anything! 😢 Any luck from anyone else?

**Comment by GitMurf** [comment]
Oh wow @pidgeon777 @smjonas ... I finally stumbled upon the correct answer! It is not `previewheight` that controls `inccommand` preview window size. It is actually the `cmdwinheight` which is the same window you can navigate through your cmdline history in.

Here is the brief reference to it: https://neovim.io/doc/user/options.html#'cmdwinheight'

And simply need to do `set cmdwinheight=20` for example.

**Comment by smjonas** [comment]
Thanks for letting us know, I didn't know that! This could be useful to add to the readme

**Pull request merged**
